In [117]:
import csv
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.metrics.pairwise import cosine_similarity

In [118]:
documentos = [
    "Historia de Madrid: Madrid, la capital de Espana, tiene una rica historia que se remonta al siglo IX. La ciudad fue fundada por los musulmanes, y su nombre proviene del arabe Majrit que significa fuente de agua. A lo largo de los siglos, Madrid se ha convertido en un centro politico, economico y cultural de Espana",
    "El Palacio Real: El Palacio Real de Madrid es una de las residencias oficiales de la familia real espanola, aunque ahora se usa principalmente para ceremonias de estado. Con mas de 3,000 habitaciones, es el palacio real mas grande de Europa Occidental y un testimonio del esplendor y la historia de Espana.",
    "Museo del Prado: El Museo del Prado es uno de los museos mas famosos del mundo y un destino imprescindible para los amantes del arte que visitan Madrid. Alberga una impresionante coleccion de obras de Velazquez, Goya, El Greco y otros maestros europeos.",
    "Parque del Retiro: El Parque del Retiro es el pulmon verde de Madrid. Antiguamente perteneciente a la monarquia espanola, este parque de 118 hectareas ofrece un respiro de la vida urbana con sus estanques, jardines y el Palacio de Cristal.",
    "Gastronomia Madrilena: Madrid es famosa por su vibrante escena gastronomica que incluye desde tapas en pequenos bares hasta restaurantes de alta cocina. Platos tipicos como el cocido madrileno y las patatas bravas son esenciales para cualquier visitante.",
    "Gran Via: La Gran Via es una de las calles mas famosas de Madrid, conocida por sus tiendas, teatros y arquitectura emblematica. Este bullicioso bulevar es un punto de encuentro para turistas y locales por igual.",
    "Real Madrid y el Estadio Santiago Bernabeu: El Real Madrid, uno de los clubes de futbol mas famosos y exitosos del mundo, juega sus partidos en el Estadio Santiago Bernabeu. Este estadio es una meca para los aficionados al futbol y ofrece tours que permiten a los visitantes explorar su rica historia.",
    "Navidad en Madrid: Durante la temporada navidena, Madrid se transforma con mercados festivos, luces deslumbrantes y decoraciones. La Plaza Mayor se convierte en un enorme mercado de Navidad, donde se pueden encontrar todo tipo de regalos y delicias tradicionales.",
    "Nochevieja en Puerta del Sol: La Puerta del Sol es el corazon de Madrid y el lugar donde miles se reunen cada Nochevieja para dar la bienvenida al ano nuevo. Comer las doce uvas de la suerte al son de las campanadas del reloj es una tradicion que todos deberian experimentar.",
    "Madrid Rio: Madrid Rio es un parque lineal a lo largo del rio Manzanares y un ejemplo perfecto de como la ciudad ha transformado areas industriales en espacios verdes vibrantes. Es un lugar popular para caminar, andar en bicicleta y disfrutar de actividades al aire libre.",
    "Historia de Dortmund: Dortmund, situada en la region del Ruhr en Alemania, tiene una historia que se remonta al ano 882. Originalmente una pequena villa, Dortmund crecio para convertirse en una importante ciudad industrial, especialmente conocida por su produccion de acero y cerveza.",
    "Westfalenpark: Westfalenpark es uno de los parques urbanos mas grandes de Europa y un lugar destacado para los visitantes en Dortmund. El parque es famoso por su Rosarium, que alberga una de las colecciones mas extensas de rosas en el mundo, y la torre Florian, que ofrece vistas panoramicas de la ciudad.",
    "Museo del Futbol Aleman: Inaugurado en 2015, el Museo del Futbol Aleman ofrece una experiencia interactiva que celebra la rica historia del futbol aleman. Ubicado en Dortmund, el museo atrae a aficionados de todo el mundo y destaca por sus exposiciones que cuentan desde los primeros dias del deporte hasta los triunfos en Copas del Mundo.",
    "Mercado de Navidad de Dortmund: El Mercado de Navidad de Dortmund es uno de los mas grandes y mas visitados de Alemania. Con su gigantesco arbol de Navidad, posiblemente el mas alto de los mercados navidenos del pais, y mas de 300 puestos que venden artesanias, alimentos y bebidas tradicionales, es un evento imperdible durante la temporada festiva.",
    "U-Tower - Centro de Arte y Creatividad: El U-Tower, una antigua cerveceria reconvertida, es ahora un centro dinamico de arte y creatividad. Alberga el Museo Ostwald, espacios de exposiciones y estudios de artistas, y es un simbolo de la transformacion cultural de Dortmund.",
    "Borussia Dortmund y el Signal Iduna Park: Borussia Dortmund es uno de los clubes de futbol mas populares y exitosos de Alemania. El equipo juega sus partidos en casa en el Signal Iduna Park, conocido por su increible atmosfera y el famoso 'Muro Amarillo', la tribuna sur que alberga a 25,000 aficionados apasionados.",
    "La cerveceria Dortmund: Dortmund tiene una larga tradicion cervecera, y la visita a una de sus muchas cervecerias es una parada obligatoria. Las cervecerias ofrecen tours que incluyen degustaciones de cervezas locales como Dortmunder Export, una lager que es un orgullo de la ciudad.",
    "La Reinoldikirche: La iglesia de San Reinold es el edificio mas antiguo de Dortmund, datando del siglo XIII. Es un punto de referencia historico importante y ofrece a los visitantes una mirada al pasado medieval de la ciudad.",
    "Dortmund durante la Segunda Guerra Mundial: Dortmund fue un objetivo significativo durante los bombardeos de la Segunda Guerra Mundial debido a su industria pesada. Hoy en dia, varios monumentos y museos ofrecen reflexiones sobre este periodo y sus efectos en la ciudad.",
    "Zoologico de Dortmund: El Zoologico de Dortmund es un lugar excelente para familias y amantes de la naturaleza. Con mas de 1,500 animales y un enfoque especial en la conservacion de especies amenazadas, el zoologico proporciona una experiencia educativa y entretenida."
]

In [119]:
diccionario = [
    "Turismo",
    "Historia",
    "Guerra",
    "Futbol",
    "Realeza",
    "Gastronomia",
    "Cultura",
    "Naturaleza",
    "Arquitectura",
    "Comercio",
    "Festividades",
    "Transporte",
    "Educacion",
    "Tecnologia",
    "Deportes",
    "Religion",
    "Entretenimiento",
    "Salud",
    "Industria",
    "Urbanismo"
]

In [120]:
def contar_terminos(documentos, diccionario):
    matriz = []
    for documento in documentos:
        recuento = []
        for termino in diccionario:
            recuento.append(documento.lower().count(termino.lower()))  # Convertir todo a minúsculas para coincidir
        matriz.append(recuento)
    return matriz

In [121]:
for fila in matriz_recuentos:
    print(fila)

[0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0,

In [122]:
# Obtener la matriz de recuentos
matriz_recuentos = contar_terminos(documentos, diccionario)

In [123]:
# Imprimir la matriz de recuentos
for fila in matriz_recuentos:
    print(fila)

[0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0,

In [124]:
query = ["Historia medieval de las ciudades europeas",
         "Principales destinos turisticos en Europa",
         "Influencia de la realeza en la cultura europea",
         "Importancia de los parques urbanos en las ciudades",
         "Gastronomia tipica en capitales europeas",
         "Eventos deportivos iconicos en Europa",
         "Celebraciones de Navidad en ciudades europeas",
         "Museos de arte importantes en Europa",
         "Efectos de la Segunda Guerra Mundial en ciudades europeas",
         "Arquitectura historica en ciudades europeas",
         "Clubes de futbol famosos y sus estadios en Europa",
         "Transformacion urbana y regeneracion de espacios",
         "Tradicion cervecera en ciudades europeas",
         "Mercados y comercio tradicional en Europa",
         "Centros de arte y creatividad en ciudades modernas",
         "Actividades de ocio y entretenimiento en ciudades metropolitanas",
         "Conservacion de la naturaleza y la vida silvestre en zonas urbanas",
         "Planificacion de eventos culturales y festivales en ciudades",
         "Desarrollo del transporte y la infraestructura urbana",
         "Impacto de la tecnolog´ıa en la vida urbana"
]

In [125]:
def contar_terminos_query(query, diccionario):
    matriz_query = []
    for consulta in query:
        recuento = []
        for termino in diccionario:
            recuento.append(consulta.lower().count(termino.lower()))  # Convertir todo a minúsculas para coincidir
        matriz_query.append(recuento)
    return matriz_query

In [126]:
# Obtener la matriz de recuentos para el query
matriz_recuentos_query = contar_terminos_query(query, diccionario)

In [127]:
# Imprimir la matriz de recuentos del query
for fila in matriz_recuentos_query:
    print(fila)

[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1,

In [128]:
distance = cosine_similarity(matriz_recuentos, matriz_recuentos_query)

In [129]:
print(distance)

[[0.89442719 0.         0.31622777 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.4472136
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.     

In [130]:
top = []
for fila in distance:
  index = np.argsort(fila)[-3:][::-1]
  top.append(fila[index])

In [131]:
query_matrix = np.array(query)
top_3_matrix = np.array(top)

In [132]:
concatenated_matrix = np.empty((len(query_matrix), 2), dtype=object)

In [133]:
for i in range(len(query_matrix)):
    concatenated_matrix[i] = [query_matrix[i], top_3_matrix[i]]

In [134]:
print(concatenated_matrix)

[['Historia medieval de las ciudades europeas'
  array([0.89442719, 0.4472136 , 0.31622777])]
 ['Principales destinos turisticos en Europa' array([1., 0., 0.])]
 ['Influencia de la realeza en la cultura europea' array([0., 0., 0.])]
 ['Importancia de los parques urbanos en las ciudades'
  array([0., 0., 0.])]
 ['Gastronomia tipica en capitales europeas' array([1., 0., 0.])]
 ['Eventos deportivos iconicos en Europa' array([1., 0., 0.])]
 ['Celebraciones de Navidad en ciudades europeas'
  array([0.89442719, 0.4472136 , 0.        ])]
 ['Museos de arte importantes en Europa' array([0., 0., 0.])]
 ['Efectos de la Segunda Guerra Mundial en ciudades europeas'
  array([0., 0., 0.])]
 ['Arquitectura historica en ciudades europeas' array([0., 0., 0.])]
 ['Clubes de futbol famosos y sus estadios en Europa'
  array([0.89442719, 0.        , 0.        ])]
 ['Transformacion urbana y regeneracion de espacios' array([0., 0., 0.])]
 ['Tradicion cervecera en ciudades europeas'
  array([0.9486833 , 0.3162

In [135]:
df = pd.DataFrame(concatenated_matrix)
df.to_csv("vect_normalized.csv", index=True)